dist: xenial
language: c
env:
  global:
    - GAP_PKGS_TO_CLONE="datastructures"
    - GAP_PKGS_TO_BUILD="io profiling datastructures json digraphs orb grape"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: CFLAGS="-O2"

branches:
        #  only:
        #    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
