name: BacktrackKit
version: 0.6.2
date: 2022-01-28
description: |
    An extensible, easy to understand backtracking framework

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf A. Wilson
      url: https://wilf.me

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf A. Wilson
      url: https://wilf.me

contributors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de

GAP: ">= 4.11"

needed-pkgs:
    - name: "datastructures"
      version: ">=0.2.6"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">=1.1.1"
      url: "https://digraphs.github.io/Digraphs"
    - name: "images"
      version: ">=1.3.0"
      url: "https://gap-packages.github.io/images/"
    - name: "primgrp"
      version: ">=3.4.0"
      url: "https://gap-packages.github.io/primgrp/"

www: https://peal.github.io/BacktrackKit
readme: README.md
packageinfo: https://peal.github.io/BacktrackKit/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/peal/BacktrackKit/releases/download/v0.6.2/BacktrackKit-0.6.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>JW22</span>]   <b class='BibAuthor'>Jefferson, C. and Wilson, W. A.</b>,
     <i class='BibTitle'>BacktrackKit, An extensible, easy to understand backtracking framework,
             Version 0.6.2</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://peal.github.io/BacktrackKit">https://peal.github.io/BacktrackKit</a></span>.
    </p>
    

bibtex: |
    @misc{ BacktrackKit0.6.2,
      author =           {Jefferson, C. and Wilson, W. A.},
      title =            {{BacktrackKit},  An  extensible,  easy  to  understand
                          backtracking framework, {V}ersion 0.6.2},
      month =            {Jan},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href            {https://peal.github.io/BacktrackKit}
                          {\texttt{https://peal.github.io/}\discretionary
                          {}{}{}\texttt{BacktrackKit}}},
      printedkey =       {JW22}
    }

